#!/bin/bash

if [ -z "$1" ]; then
    # display usage if no parameters given
    echo "Usage: create <file_name>"
else
    curl -H "Authorization: token YOURTOKEN" --data '{"name":"'"$1"'", "private":"true"}' https://api.github.com/user/repos
    mkdir ~/Documents/Workspace/$1
    cd ~/Documents/Workspace/$1
    git init
    git remote add origin git@github.com:Strampt/$1.git
    touch README.md
    git add .
    git commit -m "Initial commit"
    git push -u origin master
    code .
fi
